### ISSUE TITLE
1 - Intro, `inf_mr()`, YAML setup

### ISSUE THREAD

**Issue by gadenbuie** [presentable-user2021/website#3]
- [x] Slides
- [x] Activity Post
- [x] Supporting Materials
##  Goal

Preview a slide deck with inf_mr() that has a customized title slide and helpful setup code chunk
- Use `infinite_moon_reader()` for quick iteration with xaringan slides
- Setup for success using xaringan's built-in settings

## Material

- review YAML 
- review content classes (e.g. `.pull-left[ ]`, class: inverse)
- review syntax (e.g. `---` is a new slide, `???` adds presenter notes)

## Activity ideas
- run `inf_mr()`
- adjust slide ratio
- customize parameters in YAML
- create basic title slide using parameters and content classes

**Comment by gadenbuie** [comment]
@spcanelon It just occurred to me that you should probably mention how to restart the R session, Since it's the easiest way to stop infinite moon reader, we'll need learners to restart their session often.

**Comment by spcanelon** [comment]
Agreed!

**Comment by spcanelon** [comment]
You think restarting the R session is easier than `servr::stop_daemon()` ? I guess that's not the easiest to remember

**Comment by gadenbuie** [comment]
Yeah and the message reminding you to call `servr::daemon_stop()` goes by very quickly, too. But most of all because it will help us start each activity with a clean slate.

**Comment by spcanelon** [comment]
Lol see I even remembered it wrong just there. And yes, good point. Session restarts it is!
