### ISSUE TITLE
Fix slide preview image in metadata

### ISSUE THREAD

**Issue by gadenbuie** [presentable-user2021/website#61]
Probably a small typo in the URL to the preview image

![image](https://user-images.githubusercontent.com/5420529/124642406-d0b85c00-de5d-11eb-8bdc-155c32460fa1.png)

**Comment by spcanelon** [comment]
@gadenbuie you were right, it's a typo! I can fix it https://github.com/presentable-user2021/website/blob/528e3ac1c442329c8b58d756f03d72af38f55ab7/static/slides/R/components.R#L29

**Comment by gadenbuie** [comment]
Yup 🤦

And no worries, I've got it in a local branch I'm close to wrapping up
