### ISSUE TITLE
Update info in sidebar and Act pages

### ISSUE THREAD

**Issue by spcanelon** [presentable-user2021/website#67]
- Change "break"s in schedule to "intermission" 🎭 
- Add credit to [Rachel Hudson](https://lemur.duke.edu/100-lemurs/) to each Act for her beautiful lemur illustrations 👩🏽‍🎨

**Comment by gadenbuie** [comment]
Good news, we do credit Rachel Hudson on the act pages, but feel free to spruce it up! 🎨 

https://github.com/presentable-user2021/website/blob/bb749b6c0f7a0a086b0fa849ef85f2a155e99b31/content/materials/act-01/_index.md#L29

**Comment by spcanelon** [comment]
I just noticed that! I am going to extend the wording to "all lemur illustrations feature on this site and in the materials" because they make frequent appearances in my slides and materials (I'll need to update the Materials repo too)
