### ISSUE TITLE
4 - Effective Communication

### ISSUE THREAD

**Issue by gadenbuie** [presentable-user2021/website#7]
- [x] Slides
- [x] Activity Post
- [x] ~~Supporting Materials~~
## Goal

Understand how to organize content to help focus your audience's attention

## Material

- using content classes
- writing descriptive titles (i.e. give your audience the answer)
- add presenter notes
- use incremental reveals (a11y caveat here) 
- declutter
- if it's not critical don't include it (use backup slides)
- present graph & html table versions (with backup slides, but panelsets could also be good for this)

## Activity idea
- identify and talk through all of the different ways an ineffective slide could be made better. what xaringan tools do you already have that you could use?

**Comment by gadenbuie** [comment]
For a motivating activity in this section, you could do a semi-interactive activity using a few slides inspired by [Can't Unsee](https://cantunsee.space/). The idea would be to put screenshots of two slides next to each other and the audience picks the one with "more correct" design. The first one would be very easy but the last one would be more subtle. What I love about that page is that it helps develop design intuition — we're all pattern matching machines and we're inherently drawn to good design. Also it gives you a chance to quickly touch on the things you want to talk about in this section without having to spell it out in bullet points.

**Comment by spcanelon** [comment]
Yep, that was the plan! I had outlined this in the project board and was thinking to use side-by-side screenshots or panelsets
> identify and talk through all of the different ways an ineffective slide could be made better. what xaringan tools do you already have that you could use?
